### ISSUE TITLE
LCH values accuracy

### ISSUE THREAD

**Issue by romashamin** [dokozero/okcolor#1]
Hi there! Thank you for the plugin 🙌

I noticed that [lch.oklch.com](https://lch.oklch.com/#60.03678430650251,85.34513931186946,341.99900497617034,100) and the okColor plugin show really different values for the LCH color mode. E. g. 105 and 26.3 for Chroma.
<img width="915" alt="image" src="https://github.com/dokozero/okcolor/assets/1148914/5a30900d-37eb-4391-9195-f9a124c70240">

What could be the reason?

**Comment by romashamin** [comment]
Uh, nevermind, I just figured out that 26.3 is actually 0.26281345825005464 and also it’s OKLCH, not LCH model.

**Comment by dokozero** [comment]
Hello, indeed 🙂 FYI I'm working now on adding proper P3 support and the choice to manipulate OkLCH values like on oklch.com, you can check the develop branch for a sneak peek.
