### ISSUE TITLE
The field order for OKLCH

### ISSUE THREAD

**Issue by romashamin** [dokozero/okcolor#2]
Hey! Thanks for the update that brings P3. I’m continuing to test it, but at first glance, it looks great!

Every time I use the plugin, I have to wrap my head around this control.

<img width="545" alt="image" src="https://github.com/dokozero/okcolor/assets/1148914/0e0dbe5d-9474-40a3-8c16-f36340f04027">

The order here is H, C, and L. This order contradicts the parameter order in the CSS notation and even the space name: LCH.

I would suggest changing the field order according to the selected color space. So it would be H, S, L for HSL, and L, C, H for OKLCH.

**Comment by dokozero** [comment]
Hi, for that you can use OkLCH (CSS) mode from the models' dropdown, as explained in [plugin's page](https://www.figma.com/community/plugin/1173638098109123591/OkColor) (FAQ > "Why is there "OkLCH" and "OkLCH (CSS)"?") I've made the choice to keep the simplified OkLCH notation with inverted order for users that come from years of using HSL 🙂.

**Comment by romashamin** [comment]
Hm, got it, thank you.

What’s bothering me is that when someone chooses the OKLCH mode, they expect to get conventional LCH experience. However, in the plugin, they will get an unusual parameter order and an unusual Chroma value formatting.

Furthermore, I believe it would be better if all tools look and work consistently. Introducing unconventional variations might hinder user adoption.

What do you think?

**Comment by dokozero** [comment]
Indeed, I'm thinking about it.

I kept this value for users that were using it before the last update, as I see it, many designers are still used to HSL/HSB models and if they want the true CSS formatting they can choose "OkLCH (CSS)".

However, I agree it can bring confusion on why there are two notations with one that's not conventional.

What I'm seeing for next update is to only have "OkLCH" in the dropdown which by default would be in the correct CSS notation and add a new settings screen in the plugin with the choice to change the order and value formatting if the user wants it (and possibly others options like changing the format of "88.4%" to 0.884 for L value).
