### ISSUE TITLE
Chroma value formatting

### ISSUE THREAD

**Issue by romashamin** [dokozero/okcolor#3]
The Chroma value looks confusing, because it’s actually 0.319.

<img width="472" alt="image" src="https://github.com/dokozero/okcolor/assets/1148914/e7178c5e-8dbc-4ff0-881b-0fe244936d23">

Is there a strong reason to format it as 31.9?

**Comment by dokozero** [comment]
Yep, for real values it's better to use "OkLCH (CSS)" mode, see comment on #2 .

**Comment by romashamin** [comment]
Sure, let’s then close this one and continue in #2.
