### ISSUE TITLE
WebGL sRGB rendering bug in Chrome and Safari

### ISSUE THREAD

**Issue by dokozero** [dokozero/okcolor#6]
Hello @freydev I'm going to need your help again.

I just released a new version and found a bug in OkLCH's render, I'm not sure if it was there before when we released version 5, maybe Chrome changed something meanwhile in their WebGL engine.

**On Chrome and Safari (macOS)**
![chrome-safari](https://github.com/dokozero/okcolor/assets/17993323/6b694a69-5d7a-4daf-8dd4-ce6aaa36df83)

**On Figma desktop, Firefox and Edge (macOS)**
![figma-desktop-firefox-edge](https://github.com/dokozero/okcolor/assets/17993323/62a05a5e-8e58-407e-8831-0b57c0028b7d)

 I reverted the update to see if it was present on the last release (5), tested on Chrome and yes, same weird bug:
![version5-chrome](https://github.com/dokozero/okcolor/assets/17993323/163f21ac-ed3f-4e75-95a9-581be33d6d84)

It only happens in sRGB, P3 is fine, here is a capture from Chrome:
![chrome-safari-p3](https://github.com/dokozero/okcolor/assets/17993323/0192da77-b559-470b-8fa2-1f959709fd9a)

I looked into the code, especially in f_shader.glsl but I'm not that familiar with WebGL, If you know where it can come from that would be helpful (you'll see that I refactored the whole code and it's now easier to read 👍).

If you need to push a new test version in prod tell me as we can't test dev version in Chrome but only in desktop app which is a shame to debug 😔 . Thanks in advance for your time.

**Comment by dokozero** [comment]
Found the problem (by isolating color picker component on a new vite build to run it directly in Chrome), it was on the gamma correction part, appears to be with how pow() handle negative numbers in Chrome/Safari, so by using this another method it works.

```GLSL
col = exp(log(col) * (1./2.2)); // New way
```
```GLSL
col = pow(col,vec3(1./2.2)); // Old way
```

**Comment by qinyiyao** [comment]
Problem still exists for sRGB but not P3. 

Although, P3 has its own bug, albeit less confusing.

<img width="267" alt="CleanShot 2023-11-09 at 23 54 32@2x" src="https://github.com/dokozero/okcolor/assets/6311717/c296f217-21fd-4de9-85dc-258e5bbbbf81">

```
Figma Desktop App version 116.14.9
macOS 13.4.1 (c) (22F770820d)
```

(Incredible plugin, by the way! It's a very effective teaching tool as well.)

**Comment by dokozero** [comment]
Hello @qinyiyao,

Thanks for your feedback and your sponsor, that's much appreciated!

Regarding the bug, with sRGB you have the wrong rendering as the first capture while using Figma desktop App? If yes can I see a capture?

Regarding P3, this is weird because I don't have it (I'm also on macOS and with Figma App):

![Screenshot 2023-11-10 at 9 43 16 AM](https://github.com/dokozero/okcolor/assets/17993323/c6e4247a-c717-4320-805b-4a4039e2c8f4)

Do you have the same bug on a browser? And what about on another machine if you have the possibility?

Thanks again.

**Comment by qinyiyao** [comment]
> Regarding the bug, with sRGB you have the wrong rendering as the first capture while using Figma desktop App? If yes can I see a capture?

Here’s what it looks like on that device (Intel Core i7 + AMD Radeon Pro 5300M):

![CleanShot 2023-11-11 at 14 06 57](https://github.com/dokozero/okcolor/assets/6311717/f91d204e-6244-4b6d-b1f5-e52ff0e57761)
![CleanShot 2023-11-11 at 14 11 08](https://github.com/dokozero/okcolor/assets/6311717/615b1c52-332b-4668-a1bf-05d2f0dbbeb2)

Both issues appears in Chrome (119.0.6045.105 (x86_64)).

Both issues do not appear in Safari (16.5.2 (18615.2.9.11.10)). (But there’s a separate problem with Safari with sliders.)

Both issues do not appear on an Apple Silicon device in all settings.

——

I think your latest development branch fixes the bigger problem in sRGB mode, so both modes have the same smaller problem now:

![CleanShot 2023-11-11 at 14 51 02@2x](https://github.com/dokozero/okcolor/assets/6311717/e25a28c4-06e2-450c-b2f3-eaf72bae79ca)
![CleanShot 2023-11-11 at 14 53 44@2x](https://github.com/dokozero/okcolor/assets/6311717/5042878d-0a0c-4f11-9ae0-4396750f17a3)

**Comment by dokozero** [comment]
Thanks for all these details, that's very useful as I only have Silicon hardware to develop and debugging WebGL is quite cumbersome 🥲.

I've been able to reproduce the bug and normally it's fixed on the last build in develop, can you try again please ?

(For Safari sliders, indeed it's already on my todo list).

**Comment by dokozero** [comment]
Hello @qinyiyao, I've just released a new version in prod, normally the bug is fixed, but I let you confirm that on your hardware then I'll close the issue, thanks 🙏 .

**Comment by qinyiyao** [comment]
All issues are fixed in the new release! Thanks.

**Comment by dokozero** [comment]
🎉 nice, thanks again for your help!
